### PR TITLE
Add new note functionality, Fixes from note listing and deletion

### LINKED ISSUE #3: Create new note UI

### PR DESCRIPTION
**Pull request by mohitharshan123**
Closes #3

### CODE REVIEW

File: app/javascript/src/components/Dashboard/Notes/index.jsx [hunk 1]
```diff
@@ -1,10 +1,12 @@
 import React, { useState, useEffect } from "react";
-import notesApi from "apis/notes";
 import { Button, PageLoader } from "neetoui";
-import EmptyState from "components/Common/EmptyState";
-import EmptyNotesListImage from "images/EmptyNotesList";
 import { Header, SubHeader } from "neetoui/layouts";
+
```
Comment (karthiknmenon) [inline app/javascript/src/components/Dashboard/Notes/index.jsx:4]: Please remove this line break here.

File: app/javascript/src/components/Dashboard/Notes/index.jsx [hunk 2]
```diff
@@ -1,10 +1,12 @@
...
 import { useNotesState } from "contexts/notes";
+import EmptyState from "components/Common/EmptyState";
+import EmptyNotesListImage from "images/EmptyNotesList";
+import notesApi from "apis/notes";
+import sortOptions from "constants/sortOptions";
```
Comment (karthiknmenon) [inline app/javascript/src/components/Dashboard/Notes/index.jsx:9]: Please add a line break here to separate relative/package imports and absolute imports.

File: app/javascript/src/components/Dashboard/Notes/NoteTable.jsx [hunk 3]
```diff
@@ -108,16 +121,14 @@ export default function NoteTable({
...
-                        onClick={() => {
-                          setShowDeleteAlert(true);
-                          setSelectedRowID(note.id);
-                        }}
-                        className="ri-delete-bin-5-line ri-lg text-gray-600 hover:text-gray-900"
-                      ></i>
+                      <Button
+                        onClick={() => handleItemDeleteClick(note)}
+                        className="ri-delete-bin-5-line ri-lg"
+                        style="text"
```
Comment (karthiknmenon) [inline app/javascript/src/components/Dashboard/Notes/NoteTable.jsx:130]: Shouldn't it be `style="icon"`?

File: app/javascript/src/components/Dashboard/Notes/NoteTable.jsx [hunk 4]
```diff
@@ -108,16 +121,14 @@ export default function NoteTable({
                       position="bottom"
                       className="ml-auto"
                     >
-                      <i className="ri-pencil-line ri-lg text-gray-600 hover:text-gray-900"></i>
+                      <Button className="ri-pencil-line ri-lg " style="text" />
```
Comment (karthiknmenon) [inline app/javascript/src/components/Dashboard/Notes/NoteTable.jsx:124]: Shouldn't it be `style="icon"`?

File: app/javascript/src/components/Dashboard/Notes/NoteTable.jsx [hunk 5]
```diff
@@ -50,45 +74,34 @@ export default function NoteTable({
...
+                  <label key={note.tag.id}>
+                    <Badge
+                      color={
+                        note.tag.value == "internal"
+                          ? "green"
+                          : note.tag.value == "agile"
+                            ? "blue"
+                            : "red"
+                      }
+                    >
```
Comment (karthiknmenon) [inline app/javascript/src/components/Dashboard/Notes/NoteTable.jsx:101]: Please extract the logic to a function.

File: app/javascript/src/components/Dashboard/Notes/NewNoteForm.jsx [hunk 6]
```diff
@@ -1,51 +1,79 @@
 import React from "react";
-import * as yup from "yup";
-import { Formik, Form } from "formik";
-import { Input, Textarea } from "neetoui/formik";
-import { Button } from "neetoui";
-import notesApi from "apis/notes";
+import { Formik, Form, Field } from "formik";
+import { Input, Textarea, Select, Switch } from "neetoui/formik";
+import { Button, DateInput, Label, Toastr } from "neetoui";
```
Comment (karthiknmenon) [inline app/javascript/src/components/Dashboard/Notes/NewNoteForm.jsx:5]: Please remove this line break.

**Review by karthiknmenon — COMMENTED** [review]
@mohitharshan123 Please check the suggestions. 
For naming constants that are exported from a file, a general good practice is to name variables like - 

`NOTE_FORM_VALIDATION_SCHEMA` over `noteFormValidationScehma`
